# =========================
# MICRONAUT
# =========================
micronaut.application.name=doctor
micronaut.server.port=8080
micronaut.http.client.read-timeout=10s
micronaut.http.client.default-headers.User-Agent=doctor-app (ankitsubedi543@gmail.com)
micronaut.http.client.default-headers.Accept=application/json

# =========================
# SECURITY (JWT)
# =========================
# micronaut.security.authentication=bearer
# micronaut.security.token.jwt.signatures.secret.generator.secret=pleaseChangeThisSecretForANewOne
micronaut.security.intercept-url-map[0].pattern=/**
micronaut.security.intercept-url-map[0].access=isAnonymous()

# =========================
# CASSANDRA / SCYLLA
# =========================
cassandra.default.basic.session-name=defaultSession
cassandra.default.basic.contact-points[0]=localhost:9042
cassandra.default.basic.load-balancing-policy.local-datacenter=datacenter1
cassandra.default.schema-generate=NONE

# =========================
# PHOTON LOCATION SERVICE
# =========================
photon.base-url=https://photon.komoot.io/api
photon.search-limit=1
photon.user-agent=doctor-app (ankitsubedi543@gmail.com)